import { jsPDF } from "jspdf";

interface SessionData {
  patientName: string;
  therapistName: string;
  sessionCode: string;
  date: string;
  duration: string;
  notes: string;
}

export const createAndDownloadPDF = async (
  data: SessionData
): Promise<boolean> => {
  try {
    const pdf = new jsPDF({
      orientation: "portrait",
      unit: "mm",
      format: "a4",
    });

    // ==========================
    // Load Logo
    // ==========================

    const logoUrl =
      "https://res.cloudinary.com/dnzy9hf2x/image/upload/v1779179936/elmaimage_zhrx8q.png";

    const response = await fetch(logoUrl);

    if (!response.ok) {
      throw new Error("Unable to load logo");
    }

    const blob = await response.blob();

    const logoBase64 = await new Promise<string>((resolve, reject) => {
      const reader = new FileReader();

      reader.onloadend = () => resolve(reader.result as string);
      reader.onerror = reject;

      reader.readAsDataURL(blob);
    });

    // ==========================
    // Header
    // ==========================

    pdf.addImage(logoBase64, "PNG", 15, 10, 20, 20);

    pdf.setFontSize(22);
    pdf.setTextColor(125, 103, 179);
    pdf.text("Session Summary", 42, 24);

    pdf.setDrawColor(230, 230, 230);
    pdf.line(15, 35, 195, 35);

    // ==========================
    // Patient Information Card
    // ==========================

    pdf.setFillColor(248, 247, 252);
    pdf.roundedRect(15, 42, 180, 48, 4, 4, "F");

    pdf.setFontSize(12);
    pdf.setTextColor(51, 51, 51);

    pdf.text(`Client: ${data.patientName}`, 20, 55);
    pdf.text(`Date: ${data.date}`, 20, 64);
    pdf.text(`Therapist: Dr. ${data.therapistName}`, 20, 73);

    pdf.text(`Duration: ${data.duration}`, 110, 55);
    pdf.text(`Session: ${data.sessionCode}`, 110, 64);

    // ==========================
    // Notes Title
    // ==========================

    pdf.setFontSize(16);
    pdf.setTextColor(74, 59, 117);
    pdf.text("Therapy Session Notes", 15, 105);

    // ==========================
    // Notes Content
    // ==========================

    pdf.setFontSize(12);
    pdf.setTextColor(80, 80, 80);

    const wrappedText = pdf.splitTextToSize(
      data.notes || "No notes provided.",
      165
    );

    const lineHeight = 6;
    const notesHeight = Math.max(
      80,
      wrappedText.length * lineHeight + 20
    );

    pdf.setFillColor(249, 249, 249);
    pdf.roundedRect(
      15,
      112,
      180,
      Math.min(notesHeight, 120),
      4,
      4,
      "F"
    );

    let y = 124;
    const pageHeight = pdf.internal.pageSize.height;

    wrappedText.forEach((line: string) => {
      if (y > pageHeight - 25) {
        pdf.addPage();
        y = 20;
      }

      pdf.text(line, 22, y);
      y += lineHeight;
    });

    // ==========================
    // Footer
    // ==========================

    const footerY = pageHeight - 15;

    pdf.setDrawColor(235, 235, 235);
    pdf.line(15, footerY - 8, 195, footerY - 8);

    pdf.setFontSize(10);
    pdf.setTextColor(150);

    pdf.text(
      `Generated by Dr. ${data.therapistName}`,
      15,
      footerY
    );

    pdf.text(
      new Date().toLocaleString(),
      195,
      footerY,
      {
        align: "right",
      }
    );

    // ==========================
    // Download
    // ==========================

    const fileName = `session_notes_${data.sessionCode}_${Date.now()}.pdf`;

    pdf.save(fileName);

    return true;
  } catch (error) {
    console.error("PDF Generation Error:", error);

    alert(
      error instanceof Error
        ? error.message
        : "Failed to generate PDF"
    );

    return false;
  }
};